"""create destination tables

Revision ID: 270a1a2601fd
Revises: 22307f8dbf08
Create Date: 2026-06-11 21:45:22.036431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '270a1a2601fd'
down_revision: Union[str, None] = '22307f8dbf08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=20), nullable=False, comment='Original ID from dataset (e.g. LOC-001)'),
    sa.Column('slug', sa.String(length=300), nullable=False, comment='URL-friendly identifier generated from name'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tourism_zone', sa.String(length=100), nullable=True, comment='Short location label (e.g. Lembang, Ciwidey, Bandung Kota)'),
    sa.Column('synthetic_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON array of tags, e.g. ["Belanja","Indoor","Kuliner"]'),
    sa.Column('crowd_level', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distance_from_center_km', sa.Float(), nullable=True, comment='Distance from Alun-Alun Bandung in km'),
    sa.Column('coordinate_verified', sa.Boolean(), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('price_type', sa.String(length=50), nullable=True),
    sa.Column('opening_time', sa.String(length=10), nullable=True),
    sa.Column('closing_time', sa.String(length=10), nullable=True),
    sa.Column('weekday_opening_time', sa.String(length=10), nullable=True),
    sa.Column('weekday_closing_time', sa.String(length=10), nullable=True),
    sa.Column('weekend_opening_time', sa.String(length=10), nullable=True),
    sa.Column('weekend_closing_time', sa.String(length=10), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('positive_reviews', sa.Integer(), nullable=True),
    sa.Column('negative_reviews', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('avg_sentiment_score', sa.Float(), nullable=True, comment='Fallback when sentiment_score is null'),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('sentiment_available', sa.Boolean(), nullable=True),
    sa.Column('curation_action', sa.String(length=20), nullable=True, comment='keep / remove'),
    sa.Column('display_status', sa.String(length=30), nullable=True, comment='active_candidate / exclude_scope / temporarily_hidden'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='From is_active_verified; not a mandatory MVP filter'),
    sa.Column('popular_score', sa.Float(), nullable=True, comment='Calculated during CSV import (Phase 3)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_category'), 'destinations', ['category'], unique=False)
    op.create_index(op.f('ix_destinations_curation_action'), 'destinations', ['curation_action'], unique=False)
    op.create_index(op.f('ix_destinations_display_status'), 'destinations', ['display_status'], unique=False)
    op.create_index(op.f('ix_destinations_external_id'), 'destinations', ['external_id'], unique=True)
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=True)
    op.create_index(op.f('ix_destinations_tourism_zone'), 'destinations', ['tourism_zone'], unique=False)
    op.create_table('destination_facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('parking_available', sa.Boolean(), nullable=True),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('toilet_available', sa.Boolean(), nullable=True),
    sa.Column('mushola_available', sa.Boolean(), nullable=True),
    sa.Column('pet_friendly', sa.Boolean(), nullable=True),
    sa.Column('open_24h', sa.Boolean(), nullable=True),
    sa.Column('child_friendly', sa.Boolean(), nullable=True),
    sa.Column('night_available', sa.Boolean(), nullable=True),
    sa.Column('indoor_available', sa.Boolean(), nullable=True),
    sa.Column('safety_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id')
    )
    op.create_table('destination_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('primary_intent', sa.String(length=100), nullable=True, comment='Main intent from AI labeling (e.g. Alam, Belanja)'),
    sa.Column('core_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON array, e.g. ["Belanja","Indoor","Gratis"]'),
    sa.Column('secondary_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON array of secondary labels'),
    sa.Column('avoid_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON array of labels to avoid'),
    sa.Column('label_confidence', sa.Float(), nullable=True),
    sa.Column('label_source', sa.String(length=50), nullable=True, comment='auto_rule_v1 / manual_browser_review_v1'),
    sa.Column('label_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Per-label scores, e.g. {"Alam": 8.8, "Belanja": -2.0}'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id')
    )
    op.create_table('destination_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('media_available', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('maps_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('media_source', sa.String(length=100), nullable=True),
    sa.Column('place_id', sa.String(length=100), nullable=True),
    sa.Column('media_audit_status', sa.String(length=20), nullable=True, comment='accepted / manual_accepted / missing / rejected / pending'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destination_media')
    op.drop_table('destination_labels')
    op.drop_table('destination_facilities')
    op.drop_index(op.f('ix_destinations_tourism_zone'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_external_id'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_display_status'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_curation_action'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_category'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
