"""improve destination indexes and timestamps

Revision ID: e805abd6f11b
Revises: 270a1a2601fd
Create Date: 2026-06-11 22:00:16.712887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e805abd6f11b'
down_revision: Union[str, None] = '270a1a2601fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_destinations_active_popular', 'destinations', ['curation_action', 'display_status', 'popular_score'], unique=False)
    op.create_index(op.f('ix_destinations_popular_score'), 'destinations', ['popular_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_destinations_popular_score'), table_name='destinations')
    op.drop_index('ix_destinations_active_popular', table_name='destinations')
    # ### end Alembic commands ###
